# Generated by Django 5.0.1 on 2024-02-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHasEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_events', models.CharField(max_length=25, unique=True, verbose_name='Название мероприятия')),
                ('web_buyer_id', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Название собятия'),
        ),
    ]
